#!/usr/bin/bash
#
# Example:
# sudo ./end sdc1 /mnt

# https://serverfault.com/questions/338937/differences-between-dev-sda-and-dev-sda1
partition_device=$1
raw_device=${partition_device::-1}
raw_device_path=/dev/$raw_device
file_system_path=$2

echo - Raw device: $raw_device
echo - Raw device path: $raw_device_path
echo - Partition device: $partition_device
echo - File system path: $file_system_path
echo

echo Print current status
echo - Mount
mount | grep $raw_device
echo
echo - Devices
ls $raw_device_path*
echo

echo Init umount: $file_system_path
umount $file_system_path
echo Print mount status, empty string if umount was correct
mount | grep $raw_device
echo

# https://unix.stackexchange.com/questions/35508/eject-usb-drives-eject-command#83587
echo Init eject: $raw_device_path
eject $raw_device_path
echo Print devices
ls $raw_device_path*
echo

echo Init power off: $raw_device_path
# https://unix.stackexchange.com/questions/35508/eject-usb-drives-eject-command#83587
udisksctl power-off -b $raw_device_path
echo Print devices, empty string if the device was powered off correctly
udisksctl status | grep $raw_device
