#!/usr/bin/bash
#
# This script detects and manages new devices
# Detect new devices: https://wiki.archlinux.org/title/Udisks#udevadm_monitor

pathtoname() {
    udevadm info -p /sys/"$1" | awk -v FS== '/DEVNAME/ {print $2}'
}

stdbuf -oL -- udevadm monitor --udev -s block | while read -r -- _ _ event devpath _; do
    if [ "$event" = add ]; then
        devname=$(pathtoname "$devpath") # Example: /dev/sdb1
        usb $devname
    fi
done
