#!/usr/bin/bash
#
# Notify when a new device is detected

# Config
# Set the same values as you have in a terminal session
export DISPLAY=":0"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
export XDG_RUNTIME_DIR="/run/user/1000"

inotifywait -m -e create /dev/ | while read line
do
    device=$(echo $line | awk '{print $NF}')
    cd $HOME/Software/usb-linux/src/usb/
    cargo run $device
done

